Repository AY2223S2-CS2113-W13-2/tp, pull requests merged in 2023-04, with the labels that each got.

#135 Null Safety
  src/main/java/seedu/duke/data/exercisegenerator/exersisedata/ExerciseData.java
  src/main/java/seedu/duke/data/userdata/Session.java
  src/main/java/seedu/duke/data/userdata/userplan/Plan.java
  src/main/java/seedu/duke/data/userdata/userplan/UserPlan.java
  src/main/java/seedu/duke/storage/JsonUserDataLoader.java
  src/main/java/seedu/duke/storage/JsonUserPlansLoader.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
Labels: type.Bug, type.Enhancement

#176 Add PPP and bug fixes
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/_layouts/default.html
  docs/team/eangjs.md
  docs/team/eugeneang.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commons/LogMaster.java
  src/main/java/seedu/duke/data/exercisegenerator/LoadExerciseJson.java
  src/main/java/seedu/duke/data/exercisegenerator/exersisedata/ExerciseDataList.java
  src/main/java/seedu/duke/logic/commandhandler/CommandHandler.java
  src/main/java/seedu/duke/logic/commands/QuickStartCommand.java
  src/main/java/seedu/duke/storage/JsonUserCareerStorage.java
  src/main/java/seedu/duke/storage/JsonUserDataLoader.java
  src/main/java/seedu/duke/storage/JsonUserDataWriter.java
  src/main/java/seedu/duke/storage/JsonUserPlansLoader.java
  src/main/java/seedu/duke/storage/JsonUserPlansStorage.java
  src/main/java/seedu/duke/storage/JsonUserPlansWriter.java
  src/main/java/seedu/duke/storage/LocalDateAdapter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/storage/UserCareerStorage.java
  src/main/java/seedu/duke/storage/UserPlansStorage.java
  src/test/java/seedu/duke/exercisegenerator/GenerateExerciseTest.java
  src/test/java/seedu/duke/storage/TestReading.java
  src/test/java/seedu/duke/storage/TestWriting.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
Labels: type.Bug, documentation

#181 Update exception
  src/main/java/seedu/duke/logic/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/ui/ErrorMessages.java
Labels: severity.VeryLow

#186 Enhance UG
  META-INF/MANIFEST.MF
  allAchievements.txt
  docs/UG_features/achievementList.md
  docs/UG_features/workout_session.md
  docs/UserGuide.md
  src/main/java/seedu/duke/achievements/AchievementListHandler.java
  src/main/java/seedu/duke/logic/commandhandler/CommandList.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/storage/TextDataUtility.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/main/resources/META-INF/MANIFEST.MF
  src/test/java/seedu/duke/ui/TestUi.java
  text-ui-test/EXPECTED.TXT
Labels: documentation, severity.Medium

#189 Update PPP and UG for IPPT calculator feature
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/ghzr0.md
  src/main/java/seedu/duke/logic/commands/ExerciseSearchCommand.java
Labels: documentation

#191 Minor Fixes
  docs/DeveloperGuide.md
  docs/UML/Images/LoadingUserData.png
  docs/UML/Images/PlannerCommandHandler.png
  docs/UML/Images/Storage.png
  docs/UML/Images/Ui.png
  docs/UML/Images/addPlan.png
  docs/UML/Images/overall_sequence-0.png
  docs/UML/LoadingUserCareerData.puml
  docs/UML/PlannerCommandHandler.puml
  docs/UML/Storage.puml
  docs/UML/Ui.puml
  docs/UML/addPlan.puml
  docs/UML/overall_sequence.puml
  docs/UML/style.puml
  docs/UserGuide.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/achievements/AchievementType.java
  src/main/java/seedu/duke/data/exercisegenerator/LoadExerciseJson.java
  src/main/java/seedu/duke/data/exercisegenerator/exersisedata/ExerciseDataList.java
  src/main/java/seedu/duke/data/ipptcalculator/IPPTCalc.java
  src/main/java/seedu/duke/data/ipptcalculator/Scores.java
  src/main/java/seedu/duke/data/ipptcalculator/UserScore.java
  src/main/java/seedu/duke/data/userdata/IPPTSession.java
  src/main/java/seedu/duke/data/userdata/Session.java
  src/main/java/seedu/duke/data/userdata/UserCareerData.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/logic/commands/ExerciseSearchCommand.java
  src/main/java/seedu/duke/logic/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/logic/commands/IPPTCmd.java
  src/main/java/seedu/duke/logic/commands/QuickStartCommand.java
  src/main/java/seedu/duke/storage/JsonUserCareerStorage.java
  src/main/java/seedu/duke/storage/JsonUserDataLoader.java
  src/main/java/seedu/duke/storage/JsonUserDataWriter.java
  src/main/java/seedu/duke/storage/JsonUserPlansLoader.java
  src/main/java/seedu/duke/storage/JsonUserPlansStorage.java
  src/main/java/seedu/duke/storage/JsonUserPlansWriter.java
  src/main/java/seedu/duke/storage/LocalDateAdapter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/storage/UserCareerStorage.java
  src/main/java/seedu/duke/storage/UserPlansStorage.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/test/java/seedu/duke/commands/TestCommands.java
  src/test/java/seedu/duke/exercisegenerator/GenerateExerciseTest.java
  src/test/java/seedu/duke/storage/TestReading.java
  src/test/java/seedu/duke/storage/TestWriting.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
  src/test/java/seedu/duke/ui/TestUi.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, documentation

#192 Fix Achievements, update PPP, help message and UG
  allAchievements.txt
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/chubbsbunns.md
  docs/team/dylan.md
Labels: documentation, priority.Medium

#193 Update DG
  docs/DeveloperGuide.md
  docs/UML/Images/LoadingUserData-0.png
  docs/UML/Images/LoadingUserData.png
  docs/UML/Images/Storage-0.png
  docs/UML/Images/Storage.png
  docs/UML/Images/WritingUserData-0.png
  docs/UML/Images/WritingUserPlan-0.png
  docs/UML/Images/invalidFile-0.png
  docs/UML/LoadingUserCareerData.puml
  docs/UML/Storage.puml
  docs/UML/WritingUserData.puml
  docs/UML/WritingUserPlan.puml
  docs/UML/invalidFile.puml
  src/main/java/seedu/duke/storage/JsonUserPlansStorage.java
  src/main/java/seedu/duke/storage/JsonUserPlansWriter.java
Labels: documentation

#194 Style UG
  allAchievements.txt
  docs/UserGuide.md
  docs/img_1.png
Labels: documentation, priority.Low

#195 Fix achievements, add achievement tests
  allAchievements.txt
  docs/UserGuide.md
  src/main/java/seedu/duke/achievements/Achievement.java
  src/main/java/seedu/duke/achievements/AchievementDifficulty.java
  src/main/java/seedu/duke/achievements/AchievementListHandler.java
  src/main/java/seedu/duke/achievements/types/AchievementBodyPart.java
  src/main/java/seedu/duke/achievements/types/AchievementGymStatic.java
  src/main/java/seedu/duke/achievements/types/AchievementLevel.java
  src/main/java/seedu/duke/logic/commandhandler/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/storage/TextDataUtility.java
  src/test/java/seedu/duke/achievements/AchieveBodyPartAchievements.java
  src/test/java/seedu/duke/achievements/AchieveDifficultyAchievements.java
  src/test/java/seedu/duke/achievements/AchieveGymStaticAchievements.java
  src/test/java/seedu/duke/achievements/LoadAchievement.java
  src/test/java/seedu/duke/exercisegenerator/GenerateDifficultyExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateMixtureExerciseTest.java
Labels: documentation, priority.Medium, Tests

#196 Branch update v2.1
  allAchievements.txt
  docs/DeveloperGuide.md
  docs/UML/Images/architecture.png
  docs/UML/architecture.puml
  src/main/java/seedu/duke/data/userdata/UserExerciseData.java
  src/main/java/seedu/duke/logic/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/logic/commands/CompletedExerciseSearchCommand.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/main/java/seedu/duke/ui/PrintUserExerciseData.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ui/TestUi.java
Labels: documentation, feature, Tests

#213 Refactor Test Code, edit difficulty text output and refactor UG
  allAchievements.txt
  docs/UG_features/workout_session.md
  docs/UserGuide.md
  src/main/java/seedu/duke/achievements/Achievement.java
  src/main/java/seedu/duke/achievements/AchievementListHandler.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/storage/TextDataUtility.java
  src/main/java/seedu/duke/ui/ErrorMessages.java
  src/main/java/seedu/duke/ui/PrintExercises.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/test/java/seedu/duke/achievements/AchieveBodyPartAchievements.java
  src/test/java/seedu/duke/achievements/AchieveDifficultyAchievements.java
  src/test/java/seedu/duke/achievements/AchieveGymStaticAchievements.java
  src/test/java/seedu/duke/achievements/LoadAchievement.java
  src/test/java/seedu/duke/exercisegenerator/GenerateMixtureExerciseTest.java
  src/test/java/seedu/duke/ui/TestUi.java
  text-ui-test/EXPECTED.TXT
Labels: documentation, priority.Medium

#216 Finish group deliverables
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ghzr0.md
  plansData.json
  src/main/java/seedu/duke/data/ipptcalculator/IPPTCalc.java
  src/main/java/seedu/duke/data/ipptcalculator/UserScore.java
  src/main/java/seedu/duke/logic/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/logic/commands/ExerciseSearchCommand.java
  src/main/java/seedu/duke/logic/commands/IPPTCmd.java
  src/main/java/seedu/duke/ui/ErrorMessages.java
  src/main/java/seedu/duke/ui/PrintExercises.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ipptc/TestIPPT.java
  src/test/java/seedu/duke/ui/TestUi.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.sh
Labels: type.Bug, documentation, Tests

#228 Update PPP and DG
  docs/DeveloperGuide.md
  docs/UML/AchievementHandling.puml
  docs/UML/AchievementUpdate.puml
  docs/UML/Images/AchievementHandling.png
  docs/UML/Images/AchievementUpdate.png
  docs/UML/Images/overall_sequence-0.png
  docs/UML/Images/overall_sequence.png
  docs/UML/overall_sequence.puml
  docs/UserGuide.md
  docs/team/chubbsbunns.md
  docs/team/img.png
  docs/team/img_1.png
Labels: documentation, priority.High

#229 Fix DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, documentation
