Repository AY2223S2-CS2113-W13-2/tp, pull requests merged in 2023-03, with the labels that each got.

#14 Add a quick start exercise feature
  docs/README.md
  docs/UserGuide.md
  docs/_layouts/default.html
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/QuickStartCommand.java
  src/main/java/seedu/duke/ui/Greet.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#25 Categorise by body part
  docs/team/lipkuang.md
  src/main/java/seedu/duke/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/exercisegenerator/GenerateExercise.java
  src/main/java/seedu/duke/exersisedata/ExerciseData.java
  src/main/java/seedu/duke/ui/Greet.java
  src/main/java/seedu/duke/ui/PrintExercises.java
  src/main/resources/data.json
  src/test/java/seedu/duke/exercisegenerator/GenerateWorkoutTypeExerciseTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#26 Fix Filtering Bugs
  docs/AboutUs.md
  src/main/java/seedu/duke/Exceptions/DukeError.java
  src/main/java/seedu/duke/Exceptions/FilterTooManyError.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/exercisegenerator/GenerateExercise.java
  src/test/java/seedu/duke/exercisegenerator/GenerateDifficultyExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateWorkoutTypeExerciseTest.java
Labels: bug, severity.Medium

#28 Add user data writer and documentation
  build.gradle
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  libs/gson-2.8.2.jar
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/commands/QuickStartCommand.java
  src/main/java/seedu/duke/exceptions/DukeError.java
  src/main/java/seedu/duke/exceptions/FileReadError.java
  src/main/java/seedu/duke/exceptions/FilterTooManyError.java
  src/main/java/seedu/duke/exercisegenerator/GenerateExercise.java
  src/main/java/seedu/duke/exercisegenerator/ParseData.java
  src/main/java/seedu/duke/exersisedata/ExerciseDataList.java
  src/main/java/seedu/duke/storage/LoadUserData.java
  src/main/java/seedu/duke/storage/WriteUserData.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/userdata/CompletedWorkout.java
  src/main/resources/data.json
  src/test/java/seedu/duke/exercisegenerator/GenerateDifficultyExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateWorkoutTypeExerciseTest.java
Labels: bug, documentation, priority.Medium

#34 Refactor and clean up code for v1.0
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_layouts/default.html
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/exercisegenerator/GenerateExercise.java
  src/main/java/seedu/duke/exersisedata/ExerciseData.java
  src/main/java/seedu/duke/storage/LoadUserData.java
  src/main/java/seedu/duke/storage/LocalDateAdapter.java
  src/main/java/seedu/duke/storage/WriteUserData.java
  src/main/java/seedu/duke/ui/Greet.java
  src/main/java/seedu/duke/ui/PrintExercises.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/userdata/CompletedWorkout.java
  src/main/java/seedu/duke/userdata/TodoWorkout.java
  src/test/java/seedu/duke/commands/TestCommands.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  userData.json
Labels: documentation, type.Task

#39 Update (added help message)
  docs/AboutUs.md
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/exercisegenerator/GenerateExercise.java
  src/main/java/seedu/duke/ui/Bye.java
  src/main/java/seedu/duke/ui/PrintHelp.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: feature

#50 User session storage
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/SampleReadCommand.java
  src/main/java/seedu/duke/commands/SampleSavingCommand.java
  src/main/java/seedu/duke/exceptions/FileReadError.java
  src/main/java/seedu/duke/storage/LoadUserData.java
  src/main/java/seedu/duke/storage/UserCareerData.java
  src/main/java/seedu/duke/storage/WriteUserData.java
  src/main/java/seedu/duke/userdata/Session.java
  src/main/java/seedu/duke/userdata/TodoWorkout.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
  text-ui-test/EXPECTED.TXT
  userData.json
Labels: priority.High

#51 Add start and implement exercise sessions and save exercise sessions
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/storage/UserCareerData.java
  src/main/java/seedu/duke/storage/WriteUserData.java
  src/main/java/seedu/duke/ui/ErrorMessages.java
  src/test/java/seedu/duke/commands/TestCommands.java
Labels: type.Enhancement, priority.Medium, feature

#64 Add Storage UML and DG
  docs/DeveloperGuide.md
  docs/UML/Images/LoadingUserCareerData.png
  docs/UML/Images/StorageHandlerClass.png
  docs/UML/LoadingUserCareerData.puml
  docs/UML/StorageHandlerClass.puml
  docs/UML/style.puml
  docs/_config.yml
  docs/_layouts/default.html
  src/main/java/seedu/duke/commands/SampleSavingCommand.java
  src/main/java/seedu/duke/storage/LocalDateAdapter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageHandler.java
Labels: documentation, priority.Medium

#74 Add enhancement command handler states
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commandhandler/CommandHandler.java
  src/main/java/seedu/duke/commandhandler/CommandList.java
  src/main/java/seedu/duke/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/commands/CommandHandler.java
  src/main/java/seedu/duke/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/exceptions/DukeError.java
  src/main/java/seedu/duke/exceptions/ExerciseNumberInputAsStringError.java
  src/main/java/seedu/duke/exceptions/FileReadError.java
  src/main/java/seedu/duke/exceptions/FilterTooManyError.java
  src/main/java/seedu/duke/exceptions/InvalidBodyWorkoutTypeError.java
  src/main/java/seedu/duke/exceptions/InvalidDifficultyInputError.java
  src/main/java/seedu/duke/exceptions/InvalidInputError.java
  src/main/java/seedu/duke/exceptions/InvalidWorkoutTypeError.java
  src/main/java/seedu/duke/exceptions/NoOngoingExError.java
  src/main/java/seedu/duke/exceptions/OngoingExGenerationError.java
  src/main/java/seedu/duke/exceptions/OngoingExHelpError.java
  src/main/java/seedu/duke/exceptions/OngoingExHistoryError.java
  src/main/java/seedu/duke/exceptions/OngoingExProgressError.java
  src/main/java/seedu/duke/exceptions/OngoingExWriteError.java
  src/main/java/seedu/duke/exceptions/TooManyFiltersError.java
  src/main/java/seedu/duke/exceptions/UnknownFilterInputError.java
  src/main/java/seedu/duke/exercisegenerator/GenerateExercise.java
  src/main/java/seedu/duke/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/ui/ErrorMessages.java
  src/main/java/seedu/duke/util/StringSplitter.java
  src/test/java/seedu/duke/exercisegenerator/GenerateBodyExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateDifficultyExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateGymExerciseTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
Labels: type.Enhancement, priority.Medium

#83 minor updates + added comments
  src/main/java/seedu/duke/commandhandler/CommandHandler.java
  src/main/java/seedu/duke/commandhandler/PlannerCommandHandler.java
  src/main/java/seedu/duke/commands/QuickStartCommand.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/main/java/seedu/duke/ui/PrintPlanner.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/java/seedu/duke/userplan/Day.java
  src/main/java/seedu/duke/userplan/Plan.java
  src/main/java/seedu/duke/userplan/UserPlan.java
Labels: documentation

#89 Add Storage for plans
  .gitignore
  docs/DeveloperGuide.md
  docs/UML/Images/LoadingUserCareerData.png
  docs/UML/Images/StorageHandlerClass.png
  docs/UML/LoadingUserCareerData.puml
  docs/UML/StorageHandlerClass.puml
  logging.xml.lck
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/commandhandler/PlannerCommandHandler.java
  src/main/java/seedu/duke/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/commands/SampleReadCommand.java
  src/main/java/seedu/duke/commands/SampleSavingCommand.java
  src/main/java/seedu/duke/exercisegenerator/GenerateExercise.java
  src/main/java/seedu/duke/exercisegenerator/LoadExerciseJson.java
  src/main/java/seedu/duke/storage/LocalDateAdapter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageHandler.java
  src/main/java/seedu/duke/storage/UserDataLoader.java
  src/main/java/seedu/duke/storage/UserDataWriter.java
  src/main/java/seedu/duke/userplan/UserPlan.java
  src/test/java/seedu/duke/exercisegenerator/GenerateExerciseTest.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
  text-ui-test/input.txt
  text-ui-test/logging.xml
  text-ui-test/runtest.sh
Labels: documentation, priority.High

#92 Add Achievements, update DG with command handler
  docs/DeveloperGuide.md
  docs/UML/Images/CommandHandler Class.png
  docs/UML/Images/ErrorMessagesEnum.png
  logging.xml.1
  logging.xml.2
  logging.xml.3
  logging.xml.4
  src/main/java/seedu/duke/achievements/Achievement.java
  src/main/java/seedu/duke/achievements/AchievementDifficulty.java
  src/main/java/seedu/duke/achievements/AchievementListHandler.java
  src/main/java/seedu/duke/logic/commandhandler/CommandList.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/model/userdata/UserCareerData.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/TextDataUtility.java
  src/main/java/seedu/duke/ui/Bye.java
  src/main/java/seedu/duke/ui/ErrorMessages.java
  src/main/java/seedu/duke/ui/PrintExercises.java
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
Labels: documentation, priority.Low

#94 Refactor Storage (More OOP)
  .gitignore
  docs/DeveloperGuide.md
  docs/UML/Images/CommandHandler.png
  docs/UML/Images/Main-0.png
  docs/UML/Images/architecture.png
  docs/UML/Images/overall_sequence-0.png
  docs/UML/Main.puml
  docs/UML/architecture.puml
  docs/UML/overall_sequence.puml
  docs/UML/style.puml
  logging.xml.1
  logging.xml.2
  logging.xml.3
  logging.xml.4
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commons/LogMaster.java
  src/main/java/seedu/duke/data/exercisegenerator/GenerateExercise.java
  src/main/java/seedu/duke/data/exercisegenerator/LoadExerciseJson.java
  src/main/java/seedu/duke/data/exercisegenerator/exersisedata/ExerciseData.java
  src/main/java/seedu/duke/data/exercisegenerator/exersisedata/ExerciseDataList.java
  src/main/java/seedu/duke/data/exercisegenerator/exersisedata/ExerciseFilter.java
  src/main/java/seedu/duke/data/userdata/Session.java
  src/main/java/seedu/duke/data/userdata/UserCareerData.java
  src/main/java/seedu/duke/data/userdata/UserExerciseData.java
  src/main/java/seedu/duke/data/userdata/userplan/Day.java
  src/main/java/seedu/duke/data/userdata/userplan/Plan.java
  src/main/java/seedu/duke/data/userdata/userplan/UserPlan.java
  src/main/java/seedu/duke/logic/commandhandler/CommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/PlannerCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/logic/commands/Command.java
  src/main/java/seedu/duke/logic/commands/ExerciseSearchCommand.java
  src/main/java/seedu/duke/logic/commands/GenerateFilterCommand.java
  src/main/java/seedu/duke/logic/commands/HelpCommand.java
  src/main/java/seedu/duke/logic/commands/QuickStartCommand.java
  src/main/java/seedu/duke/storage/JsonUserCareerStorage.java
  src/main/java/seedu/duke/storage/JsonUserDataLoader.java
  src/main/java/seedu/duke/storage/JsonUserDataWriter.java
  src/main/java/seedu/duke/storage/JsonUserPlansLoader.java
  src/main/java/seedu/duke/storage/JsonUserPlansStorage.java
  src/main/java/seedu/duke/storage/JsonUserPlansWriter.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageHandler.java
  src/main/java/seedu/duke/storage/StorageManager.java
  src/main/java/seedu/duke/storage/UserCareerStorage.java
  src/main/java/seedu/duke/storage/UserPlansStorage.java
  src/main/java/seedu/duke/ui/PrintExercises.java
  src/main/java/seedu/duke/ui/PrintPlanner.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/TestCommands.java
  src/test/java/seedu/duke/exercisegenerator/GenerateBodyExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateDifficultyExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateGymExerciseTest.java
  src/test/java/seedu/duke/exercisegenerator/GenerateWorkoutTypeExerciseTest.java
  src/test/java/seedu/duke/storage/TestReading.java
  src/test/java/seedu/duke/storage/TestWriting.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
Labels: documentation, type.Enhancement

#101 Update User docs
  Storage.puml
  docs/DeveloperGuide.md
  docs/UG_features/planner.md
  docs/UG_features/workout_session.md
  docs/UML/LoadingUserCareerData.puml
  docs/UserGuide.md
  docs/_layouts/default.html
  docs/team/eugeneang.md
  src/main/java/seedu/duke/logic/commandhandler/CommandList.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/storage/JsonUserCareerStorage.java
  src/main/java/seedu/duke/storage/JsonUserPlansStorage.java
  src/test/java/seedu/duke/storage/UserDataStorageTest.java
Labels: type.Bug, documentation

#103 Updated Help message, and added tests
  src/main/java/seedu/duke/ui/PrintHelpMessage.java
  src/test/java/seedu/duke/commands/TestCommands.java
  src/test/java/seedu/duke/ui/TestUi.java
  text-ui-test/EXPECTED.TXT
Labels: Tests

#110 Update of doc folder
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/glenn.md
Labels: documentation

#112 Minor Fixes
  .gitignore
  docs/DeveloperGuide.md
  docs/UML/Images/LoadingUserCareerData.png
  docs/UML/Images/Storage.png
  docs/UML/Images/StorageHandlerClass.png
  docs/UML/Storage.puml
  docs/UML/StorageHandlerClass.puml
  docs/UserGuide.md
  docs/_layouts/default.html
  docs/team/eugeneang.md
  logging.xml
  logging.xml.lck
Labels: documentation

#114 Add achievement feature
  allAchievements.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/achievements/Achievement.java
  src/main/java/seedu/duke/achievements/AchievementDifficulty.java
  src/main/java/seedu/duke/achievements/AchievementListHandler.java
  src/main/java/seedu/duke/achievements/AchievementType.java
  src/main/java/seedu/duke/achievements/types/AchievementBodyPart.java
  src/main/java/seedu/duke/achievements/types/AchievementGymStatic.java
  src/main/java/seedu/duke/achievements/types/AchievementLevel.java
  src/main/java/seedu/duke/commons/LogMaster.java
  src/main/java/seedu/duke/logic/commandhandler/CommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/CommandList.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/GeneralCommandHandler.java
  src/main/java/seedu/duke/logic/commandhandler/states/ExerciseStateHandler.java
  src/main/java/seedu/duke/storage/TextDataUtility.java
  src/main/java/seedu/duke/ui/ErrorMessages.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#122 Fix session ending bugs
  allAchievements.txt
  plansData.json
  src/main/java/seedu/duke/commons/LogMaster.java
  src/main/java/seedu/duke/logic/commandhandler/ExerciseSessionCommandHandler.java
  src/main/java/seedu/duke/storage/JsonUserPlansStorage.java
Labels: type.Bug, severity.High

#126 Remove planner bugs
  plansData.json
  src/main/java/seedu/duke/data/userdata/userplan/UserPlan.java
  src/main/java/seedu/duke/logic/commandhandler/PlannerCommandHandler.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Medium

#131 Update DG to show randomness and achievementList
  docs/UserGuide.md
  plansData.json
Labels: documentation
